; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
monitor_speed = 115200
framework = arduino

; Hardware settings
  ; ToDo: figure out if the internal only applies to this upload
; board_hardware.oscillator = external
board_hardware.oscillator = internal
board_hardware.uart = ser1
board_hardware.rstpin = reset

; Build settings
build_flags =-Wall -Wextra

[env:AVR128DB48_Optiboot]
upload_protocol = arduino
platform = atmelmegaavr
board = AVR128DB48


[env:AVR128DB48_UPDI]
platform = atmelmegaavr
board = AVR128DB48
platform_packages = tool-avrdude-megaavr
upload_protocol = custom
upload_flags =
    -t
    ; use "tool-avrdude-megaavr" for the atmelmegaavr platform
    uart
    -u
    $UPLOAD_PORT
    -b
    ; $UPLOAD_SPEED
    57600
    ;460800
    ;921600
    ;1152000
    -d
    avr128db48
    --fuses
    6:0b00001100
    7:0x00
    8:0x00
    -f
    $SOURCE 
    -a 
    write
    ; -v is verbose
    -v
# upload_command = python3 -u /home/dev4/.arduino15/packages/megaTinyCore/hardware/megaavr/2.6.10/tools/prog.py -t uart -u /dev/ttyUSB0 -b 460800 -d attiny1614 --fuses 2:0x01 6:0x04 8:0x00 -f$SOURCE -a write
upload_command = python3 -u /home/dev4/.arduino15/packages/DxCore/hardware/megaavr/1.5.11/tools/prog.py $UPLOAD_FLAGS
# upload_command = python3 -u /home/dev4/.arduino15/packages/megaTinyCore/hardware/megaavr/2.6.10/tools/prog.py $UPLOAD_FLAGS

[env:nanoatmega168]
board = nanoatmega168
platform = atmelavr