; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
monitor_speed = 115200
; monitor_filters = send_on_enter

build_type = debug
; build_type = release

build_flags =
  -Wall
  -Wextra
  ; -D THING_TO_DEFINE

[env:AVR128DB48_Optiboot]
upload_protocol = arduino
platform = atmelmegaavr
board = AVR128DB48
; Hardware settings
  ; ToDo: figure out if the internal/external only applies to this upload
; board_hardware.oscillator = external
board_hardware.oscillator = internal
board_hardware.uart = ser1
board_hardware.rstpin = reset


[env:AVR128DB48_updi]
platform = atmelmegaavr
board = AVR128DB48
upload_protocol = custom
upload_command = pymcuprog erase && pymcuprog write -f $SOURCE

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
upload_protocol = arduino

[env:nanoatmega168]
platform = atmelavr
board = nanoatmega168
upload_flags =
  -v
  ; -V    ; Skip verification (never recommended but speeds up upload)
